# Generated by Django 4.2 on 2025-01-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
